apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-entry-web-hpa
spec:
  scaleTargetRef:
    # 目标 Deployment 名称
    apiVersion: apps/v1
    kind: Deployment
    name: data-entry-web-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      # 目标 CPU 利用率设置为 40%
      target:
        type: Utilization
        averageUtilization: 40