apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    # 目标 Deployment 名称
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-deployment 
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      # 当 CPU 利用率达到 50% 时触发伸缩
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      selectPolicy: Max
      stabilizationWindowSeconds: 30 
      policies:
      - type: Pods
        value: 1 # 一次最多减少 1 个 Pod
        periodSeconds: 30